Feat: update account with username
wavvapp/sac-frontend pull request #102
Opened 2024-11-05 07:59 UTC by serapieTuyishime

Closes #101

2024-11-05 14:35 UTC, mhenriette requested changes

2024-11-05 14:35 UTC, mhenriette commented on screens/Authentication/SignUp/CreateCredentials.tsx
> +      } else updateUsername()
can you use early return here

2024-11-06 08:03 UTC, Odile078 commented on screens/Authentication/SignUp/CreateCredentials.tsx
> +    navigation.navigate("Home")
Let's just navigate to the home screen and remove the `TODO`.With the currently implemented logic, we do not have a noFriends screen, we have a home page that will display different things depending on whether the user has friends or not.

2024-11-06 14:00 UTC, mhenriette requested changes

2024-11-06 14:00 UTC, mhenriette commented on screens/Authentication/SignUp/CreateCredentials.tsx
> +      } else updateUsername()
```suggestion
      if (data.message.toLowerCase() === "username already exist") {
        setIsError(true)
        return
      }
      updateUsername()
```

2024-11-08 09:02 UTC, merged