Ft/update user activity status
wavvapp/sac-frontend pull request #109
Opened 2024-11-07 11:30 UTC by igorntwari

closes #104

2024-11-07 12:53 UTC, mhenriette commented on components/lists/Friends.tsx
> +      const allFriends = response.data.map((friend: any) => ({
can you create type for this and not add any as type

2024-11-07 12:55 UTC, mhenriette commented on components/lists/Friends.tsx
> +        imageUrl: friend.profile || "",
```suggestion
        id: friend.id,
        name: friend.user.names,
        email: friend.user.email,
        username: friend.user.username,
        imageUrl: friend.user.profilePictureUrl || "",
```

2024-11-07 12:58 UTC, mhenriette commented on components/lists/Friends.tsx
> +  }, [friends])
this dependency array value is not making any difference, add `fetchFriends` function in a dependency array instead and wrap the function in a `useCallback`

2024-11-07 13:26 UTC, Odile078 requested changes

2024-11-07 13:26 UTC, Odile078 commented on components/lists/Friends.tsx
> +        selected: friends.includes(friend.friendId),
can we use the actual key from the backend data that indicated that the friends were selected to see the user's activities?

2024-11-07 14:04 UTC, serapieTuyishime requested changes

2024-11-07 14:04 UTC, serapieTuyishime commented on contexts/StatusContext.tsx
> +import React, { createContext, useContext, useState } from "react"
```suggestion
import { createContext, useContext, useState } from "react"
```

2024-11-07 14:04 UTC, serapieTuyishime commented on contexts/StatusContext.tsx
Lets use the existing "useSignal" hook, since this is all related to **updating the signal**

2024-11-07 14:04 UTC, serapieTuyishime commented on navigation/index.tsx
> +        <StatusProvider>
```suggestion
```

2024-11-07 14:04 UTC, serapieTuyishime commented on navigation/index.tsx
> +        </StatusProvider>
```suggestion
```

2024-11-07 14:04 UTC, serapieTuyishime commented on types/index.ts
> +}
This appears as a duplicate of the `User` type

2024-11-08 06:40 UTC, serapieTuyishime commented on components/lists/Signaling.tsx
> +            clearLocalStorage()
```suggestion
```

2024-11-08 06:41 UTC, serapieTuyishime commented on contexts/StatusContext.tsx
> +    })
```suggestion
```

2024-11-08 06:45 UTC, serapieTuyishime commented on service/index.ts
> +      user && (await refreshAccessToken(token))
this should receive refreshToken, not the access token

2024-11-08 08:02 UTC, serapieTuyishime approved these changes

2024-11-08 08:27 UTC, mhenriette approved these changes

2024-11-08 09:25 UTC, merged