feat: create friendship
wavvapp/sac-frontend pull request #110
Opened 2024-11-07 13:04 UTC by serapieTuyishime

Closes #107

2024-11-07 13:50 UTC, mhenriette requested changes

2024-11-07 13:50 UTC, mhenriette commented on screens/Search/index.tsx
>        const users = response.data.map((user: any) => ({
can you create type for the user

2024-11-07 18:40 UTC, mhenriette approved these changes

2024-11-08 08:28 UTC, igorntwari approved these changes

2024-11-08 09:01 UTC, merged