refactor: set  signal activity status to initials status from the backend
wavvapp/sac-frontend pull request #122
Opened 2024-11-11 13:33 UTC by igorntwari

closes #117

2024-11-11 15:29 UTC, mhenriette requested changes

2024-11-11 15:29 UTC, mhenriette commented on components/lists/Friends.tsx
> +          }
can you improve the code and not use nested ifs

2024-11-11 16:24 UTC, serapieTuyishime commented on contexts/StatusContext.tsx
> +
is this implementation different from the **fetchMySignal** function that is already existing in **useSignal**?

2024-11-12 08:21 UTC, mhenriette requested changes

2024-11-12 08:35 UTC, serapieTuyishime commented on contexts/StatusContext.tsx
> +  const [loading, setLoading] = useState(true)
```suggestion
  const [isLoading, setIsLoading] = useState(true)
```

2024-11-13 07:31 UTC, serapieTuyishime approved these changes

2024-11-13 07:42 UTC, mhenriette approved these changes

2024-11-14 09:12 UTC, merged