Fix/sign in with complete credentials
wavvapp/sac-frontend pull request #188
Opened 2024-12-02 13:24 UTC by serapieTuyishime

Closes #187

2024-12-02 15:01 UTC, igorntwari requested changes

2024-12-02 15:01 UTC, igorntwari commented on contexts/AuthContext.tsx
> +        // 202 means that the new user data has been accepted for processing.
can you remove this comment

2024-12-03 09:13 UTC, igorntwari approved these changes

2024-12-03 12:02 UTC, mhenriette approved these changes

2024-12-03 12:28 UTC, merged