fix: log in for new user inconsistency
wavvapp/sac-frontend pull request #200
Opened 2024-12-05 13:13 UTC by mhenriette

Closes #197

2024-12-09 13:22 UTC, igorntwari requested changes

2024-12-09 13:22 UTC, igorntwari commented on contexts/AuthContext.tsx
> +  signInWithGoogle: (navigation:any) => Promise<void>
can you give another type which is not any

2024-12-09 13:22 UTC, igorntwari commented on contexts/AuthContext.tsx
> +  const signInWithGoogle = async (navigation:any) => {
here also

2024-12-10 07:25 UTC, igorntwari approved these changes

2024-12-10 08:39 UTC, Odile078 approved these changes

2024-12-10 08:39 UTC, Odile078 commented on navigation/index.tsx
> +// import CustomSplashScreen from "@/screens/CustomSplashScreen"
remove the commented line

2024-12-10 09:04 UTC, merged