feat: Update user-info
wavvapp/sac-frontend pull request #56
Opened 2024-10-08 15:41 UTC by Odile078

closes #44

2024-10-15 07:27 UTC, serapieTuyishime requested changes

2024-10-15 07:27 UTC, serapieTuyishime commented on components/UserInfo.tsx
> +    color: "#000000",
Use theme

2024-10-15 07:27 UTC, serapieTuyishime commented on data/friends.ts
> +    username: "@erinwagner",
```suggestion
    username: "erinwagner",
```

2024-10-15 07:27 UTC, serapieTuyishime commented on data/friends.ts
As its unlikely that the database with store the username with a preceding "@", its better that we hardcode it in the `<UserInfo/>` component

2024-10-15 07:27 UTC, serapieTuyishime commented on components/UserInfo.tsx
> +        {username}
```suggestion
        @{username}
```

2024-10-15 07:27 UTC, serapieTuyishime commented on data/users.ts
Same for this file, remove the preceding "@" on the usernames

2024-10-15 10:38 UTC, serapieTuyishime approved these changes

2024-10-15 10:47 UTC, mhenriette approved these changes

2024-10-16 10:59 UTC, AnasAlamin approved these changes

2024-10-17 09:13 UTC, merged