feat: add share componet
wavvapp/sac-frontend pull request #61
Opened 2024-10-11 11:04 UTC by Odile078

closes #46

2024-10-15 08:24 UTC, igorntwari requested changes

2024-10-15 14:11 UTC, serapieTuyishime approved these changes

2024-10-15 15:36 UTC, igorntwari approved these changes

2024-10-16 10:55 UTC, AnasAlamin commented
why do we need a testing screen to test that? if we're not gonna use that right now, let's not

2024-10-17 09:13 UTC, merged