feat: update user status component
wavvapp/sac-frontend pull request #69
Opened 2024-10-17 13:18 UTC by mhenriette

Closes #48

2024-10-17 14:30 UTC, igorntwari requested changes

2024-10-17 14:30 UTC, igorntwari commented on components/cards/UserStatus.tsx
> +import UserAvailability from "./UserAvailability"
use dynamic render here

2024-10-17 16:10 UTC, mhenriette commented on components/cards/UserStatus.tsx
> +import UserAvailability from "./UserAvailability"
Why is it needed?

2024-10-18 08:50 UTC, Odile078 approved these changes

2024-10-18 10:26 UTC, igorntwari commented on components/cards/UserStatus.tsx
> +import UserAvailability from "./UserAvailability"
i meant to use alias import

2024-10-21 12:56 UTC, serapieTuyishime approved these changes

2024-10-21 12:56 UTC, serapieTuyishime commented on components/cards/UserStatus.tsx
> +            </>
```suggestion
          <>
            <CustomText
              size="sm"
              fontFamily="writer-mono"
              style={styles.statusText}>
              {friends.length
                ? `Visible to ${friends.length} friends`
                : "This status is not visible to anyone"}
            </CustomText>
            <CustomText
              size="sm"
              fontFamily="writer-mono"
              style={styles.statusText}>
              {visibleFriendsList
                ? `${visibleFriendsList}.`
                : "Tap to edit your preferences."}
            </CustomText>
          </>
```

2024-10-21 14:13 UTC, igorntwari approved these changes

2024-10-22 10:47 UTC, serapieTuyishime approved these changes

2024-10-22 11:17 UTC, AnasAlamin approved these changes

2024-10-22 11:17 UTC, merged