feat: update friends list with new design
wavvapp/sac-frontend pull request #70
Opened 2024-10-17 13:40 UTC by serapieTuyishime

Closes #39

2024-10-18 13:11 UTC, Odile078 commented on components/lists/Friends.tsx
> +  const [friendsList, setfriendsList] = useState(defaultUsers)
let's rename `setfriendsList` to `setFriendsList`

2024-10-21 13:22 UTC, Jonath-z commented on screens/EditSignal/index.tsx
> +          gap: 20,
I think you might need to configure the spacing as well, maybe not now.

2024-10-21 14:50 UTC, Odile078 approved these changes

2024-10-22 10:14 UTC, Jonath-z approved these changes

2024-10-22 11:15 UTC, AnasAlamin commented on components/lists/Friends.tsx
> +      <ScrollView
why did you change this to a  `ScrollView`? we can't have 2 scrollviews with the same orientation under each other.

2024-10-22 11:16 UTC, AnasAlamin requested changes
please check the comment below

2024-10-22 12:46 UTC, AnasAlamin approved these changes

2024-10-22 12:46 UTC, merged