Feat: update typography
wavvapp/sac-frontend pull request #71
Opened 2024-10-17 14:11 UTC by Odile078

closes #64

2024-10-18 12:58 UTC, serapieTuyishime requested changes

2024-10-18 12:58 UTC, serapieTuyishime commented on components/ui/Badge.tsx
> +    fontWeight: theme.fontWeight.normal.fontWeight,
This could lead to confusions

2024-10-18 12:58 UTC, serapieTuyishime commented on theme.ts
> +export const theme: Theme = {
Could you export these individualy ? like colors, fontweight, etc...

2024-10-21 14:43 UTC, serapieTuyishime approved these changes

2024-10-22 10:26 UTC, Jonath-z approved these changes

2024-10-22 11:11 UTC, AnasAlamin approved these changes

2024-10-22 12:47 UTC, merged