refactor: implement search screen on the fronend
wavvapp/sac-frontend pull request #97
Opened 2024-10-30 13:00 UTC by igorntwari

closes #95

2024-10-31 17:15 UTC, serapieTuyishime requested changes

2024-10-31 17:15 UTC, serapieTuyishime commented on screens/CustomSplashScreen/index.tsx
These comments should be removed when pushing to GH

2024-10-31 17:15 UTC, serapieTuyishime commented on screens/EditSignal/index.tsx
These changes are not necessary

2024-10-31 17:15 UTC, serapieTuyishime commented on screens/Home/index.tsx
same here, it should not be on GH

2024-10-31 17:15 UTC, serapieTuyishime commented on screens/Search/index.tsx
> +      })
```suggestion
      const response = await api.get(`/users`)
```
Since we already have request interceptors defined in `service/index.ts`

2024-10-31 17:15 UTC, serapieTuyishime commented on screens/Search/index.tsx
> +      }
This is unlikely to happen since the search screen is only rendered when "isAuthenticated" is true in the `navigation/index.tsx`file

2024-11-04 09:43 UTC, serapieTuyishime approved these changes

2024-11-05 13:34 UTC, mhenriette requested changes

2024-11-05 13:34 UTC, mhenriette commented on screens/Search/index.tsx
> +  }
can you order this and start by the function creation and call it in a useEffect later

2024-11-05 13:34 UTC, mhenriette commented on screens/Search/index.tsx
>      })
Can you not use if - else and use early returns

2024-11-06 09:03 UTC, mhenriette approved these changes

2024-11-06 10:27 UTC, serapieTuyishime commented on screens/Search/index.tsx
> +      const response = await api.get(`/api/users/`)
```suggestion
      const response = await api.get(`/users/`)
```

2024-11-06 10:28 UTC, serapieTuyishime commented on service/index.ts
> +  const url = `${process.env.API_BASE_URL}/api/auth/refresh-token`
```suggestion
  const url = `${process.env.API_BASE_URL}/auth/refresh-token`
```

2024-11-06 10:30 UTC, serapieTuyishime commented
Merged without a senior dev's approval, since this was blocking several other PRs

2024-11-06 10:30 UTC, merged